### ISSUE TITLE
E-IMZO-SERVER

### ISSUE THREAD

**Issue by hilook** [qo0p/e-imzo-doc#1]
В документации написано:

2.1. Запуск и настройка
Для запуска требуется:

JRE v1.8. (update 322) (Docker image: openjdk:8u322-oraclelinux8)
Интернет соединение до сервера vpn.e-imzo.uz:3443 (testvpn.e-imzo.uz:2443 для тестирования).
Файлы конфигурации и VPN-ключи.
Запуск выполняется командой:

java -Dfile.encoding=UTF-8 -jar e-imzo-server.jar config.properties

В связи с этим возник вопрос: где брать VPN-ключи, сам сервер e-imzo-server.jar?
А по большому счету, хотелось бы понять как развернуть сервер для верификации подписей. Как-то получилось, что описанного в пункте 2.1 недостаточно для понимания.

**Comment by qo0p** [comment]
> В документации написано:
> 
> 2.1. Запуск и настройка Для запуска требуется:
> 
> JRE v1.8. (update 322) (Docker image: openjdk:8u322-oraclelinux8) Интернет соединение до сервера vpn.e-imzo.uz:3443 (testvpn.e-imzo.uz:2443 для тестирования). Файлы конфигурации и VPN-ключи. Запуск выполняется командой:
> 
> java -Dfile.encoding=UTF-8 -jar e-imzo-server.jar config.properties
> 
> В связи с этим возник вопрос: где брать VPN-ключи, сам сервер e-imzo-server.jar? А по большому счету, хотелось бы понять как развернуть сервер для верификации подписей. Как-то получилось, что описанного в пункте 2.1 недостаточно для понимания.

Вся эта информация у нас на телеграм канале E-IMZO.  
VPN-ключи передаются после заключения договора или можете заросить тестовые VPN-ключи и тестовый PFX-ключ у Замиры (по телеграм @baxaabdu).
