### ISSUE TITLE
Автоматическое подписание 

### ISSUE THREAD

**Issue by stanislav-umanets** [qo0p/e-imzo-doc#3]
Здравствуйте. 

Есть ли способ подписать документ автоматически при помощи .pfx ключа? 
Я вызываю функцию create_pkcs7 и передаю туда хэш документа, id ключа, который получаю из функции load_key и 'no' для параметра detached. Эти действия вызывают окно которое требует ввести пароль. 

Есть ли возможность автоматически подписывать документы не запрашивая пароль?

**Comment by qo0p** [comment]
Здравствуйте.

Автоматического подписания нет, т.к. человек должен знать что он подписывает. Подпись не должна производиться без ведома человека. Такое требование было и есть при разработке E-IMZO.

**Comment by qo0p** [comment]
> Здравствуйте.
> 
> Есть ли способ подписать документ автоматически при помощи .pfx ключа? Я вызываю функцию create_pkcs7 и передаю туда хэш документа, id ключа, который получаю из функции load_key и 'no' для параметра detached. Эти действия вызывают окно которое требует ввести пароль.
> 
> Есть ли возможность автоматически подписывать документы не запрашивая пароль?

Здравствуйте.

Автоматического подписания нет, т.к. человек должен знать что он подписывает. Подпись не должна производиться без ведома человека. Такое требование было и есть при разработке E-IMZO.

**Comment by stanislav-umanets** [comment]
> > Здравствуйте.
> > Есть ли способ подписать документ автоматически при помощи .pfx ключа? Я вызываю функцию create_pkcs7 и передаю туда хэш документа, id ключа, который получаю из функции load_key и 'no' для параметра detached. Эти действия вызывают окно которое требует ввести пароль.
> > Есть ли возможность автоматически подписывать документы не запрашивая пароль?
> 
> Здравствуйте.
> 
> Автоматического подписания нет, т.к. человек должен знать что он подписывает. Подпись не должна производиться без ведома человека. Такое требование было и есть при разработке E-IMZO.

Ясно. Благодарю за ответ. Доброго времени суток.

**Comment by stanislav-umanets** [comment]
> > Здравствуйте.
> > Есть ли способ подписать документ автоматически при помощи .pfx ключа? Я вызываю функцию create_pkcs7 и передаю туда хэш документа, id ключа, который получаю из функции load_key и 'no' для параметра detached. Эти действия вызывают окно которое требует ввести пароль.
> > Есть ли возможность автоматически подписывать документы не запрашивая пароль?
> 
> Здравствуйте.
> 
> Автоматического подписания нет, т.к. человек должен знать что он подписывает. Подпись не должна производиться без ведома человека. Такое требование было и есть при разработке E-IMZO.

Ясно. Благодарю за ответ. Доброго времени суток.
