### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by MariKiss** [qo0p/e-imzo-doc#5]
Здравствуйте. Подскажите, пожалуйста.

Хочу установить E-IMZO на своем удаленном сервере для тестирования. Были настроены Docker и JRE v1.8 в нем. Что делать дальше? Откуда взять файлы конфигурации и VPN-ключи для тестирования?

Для получения файла e-imzo-server.jar необходимо заключать договор или Замира (@baxaabdu) может предоставить и этот файл?

**Comment by qo0p** [comment]
> Здравствуйте. Подскажите, пожалуйста.
> 
> Хочу установить E-IMZO на своем удаленном сервере для тестирования. Были настроены Docker и JRE v1.8 в нем. Что делать дальше? Откуда взять файлы конфигурации и VPN-ключи для тестирования?
> 
> Для получения файла e-imzo-server.jar необходимо заключать договор или Замира (@baxaabdu) может предоставить и этот файл?

Для получения файла конфигурации и VPN-ключа для тестирования напишите по телеграм Замире (@baxaabdu).
Так же ваш сервер должен быть в Узбекистане, иначе доступ закрыт.
